### ISSUE TITLE
Snoverlay CC switch

### ISSUE THREAD

**Issue by JoelPeterPage** [ryannair05/Snoverlay-2#1]
Could you please add a CC toggle for this?

I did ask Ryan years ago, but it wasn’t so important..

**Comment by JesseB0rn** [comment]
Will add it myself after my current pullrequest

**Comment by JesseB0rn** [comment]
#3 is implemented, you can test it now: https://we.tl/t-n7FK5Icauf

**Comment by JoelPeterPage** [comment]
https://we.tl/t-n7FK5Icauf

![4F64C550-2493-4DE6-BCD2-3AEDFAC7238F](https://user-images.githubusercontent.com/9304573/101432183-502d8d80-3958-11eb-914a-1c523bf6658e.png)

Perfect! Thank ya for this..

![316043B5-26F6-4F18-974F-CB1CA1CAFBD7](https://user-images.githubusercontent.com/9304573/101432211-5c194f80-3958-11eb-855a-c5e6b660291c.png)
